version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    env_file:
      - .env  
    ports:
      - "5434:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq  
    volumes: 
      - .:/usr/src/app

networks:
  default:
    external:
      name: rabbitmqNetwork  


    